#include "../include/generator_helpers.h"
#include "../include/figures.h"
#include <fstream>
#include <cmath>
#include <vector>
#include <iostream>
#include <list>
#include <sstream>
#include <array>
#include <iomanip>
#include <algorithm>
#include <cctype>
#include <unordered_map>

using namespace std;

bool verifyMetric(const string& name, float value, float min) {
    if (value < min) {
        cerr << "Error: " << name << " must be at least " << min
             << " (got " << value << ")" << endl;
        return false;
    }
    return true;
}

// ============================================================================
// writeOutput — VertList version (proper parametric UVs from the generators)
// ============================================================================

void writeOutput(const VertList& verts, const string& file) {
    string outputPath = "../../figures/" + file;
    ofstream out(outputPath);
    if (!out.is_open()) {
        cerr << "Error: Could not open file " << outputPath << endl;
        cerr << "Make sure the 'figures' directory exists!" << endl;
        return;
    }

    out << "# Generated by CG-SolarSystem\n";
    out << fixed << setprecision(6);

    for (const auto& v : verts)
        out << "v "  << v.x  << ' ' << v.y  << ' ' << v.z  << '\n';
    for (const auto& v : verts)
        out << "vt " << v.u  << ' ' << v.v  << '\n';
    for (const auto& v : verts)
        out << "vn " << v.nx << ' ' << v.ny << ' ' << v.nz << '\n';

    int n = (int)verts.size();
    for (int i = 0; i + 2 < n; i += 3)
        out << "f "
            << i+1 << '/' << i+1 << '/' << i+1 << ' '
            << i+2 << '/' << i+2 << '/' << i+2 << ' '
            << i+3 << '/' << i+3 << '/' << i+3 << '\n';

    out.close();
    cout << "Figure generated successfully: " << outputPath << endl;
    cout << "Total: " << verts.size() << " vertices ("
         << verts.size() / 3 << " triangles)" << endl;
}

// ============================================================================
// Legacy scatter support — kept to preserve scatter functionality
// ============================================================================

namespace {

using Vec3 = array<float, 3>;
using Vec2 = array<float, 2>;

static Vec3 parseVec3(const string& line) {
    istringstream iss(line);
    Vec3 p{};
    iss >> p[0] >> p[1] >> p[2];
    return p;
}

static Vec3 subtractVec(const Vec3& a, const Vec3& b) {
    return {a[0]-b[0], a[1]-b[1], a[2]-b[2]};
}

static Vec3 crossVec(const Vec3& a, const Vec3& b) {
    return {a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]};
}

static void normalizeVec(Vec3& v) {
    float len = sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);
    if (len > 1e-6f) { v[0]/=len; v[1]/=len; v[2]/=len; }
    else v = {0,0,1};
}

static Vec2 projectTexCoord(const Vec3& p, const Vec3& n) {
    float ax = fabs(n[0]), ay = fabs(n[1]), az = fabs(n[2]);
    if (ax >= ay && ax >= az) return {p[1], p[2]};
    if (ay >= ax && ay >= az) return {p[0], p[2]};
    return {p[0], p[1]};
}

static array<Vec2, 3> buildTriangleUVs(const Vec3& p0, const Vec3& p1, const Vec3& p2, const Vec3& n) {
    array<Vec2, 3> proj = {projectTexCoord(p0,n), projectTexCoord(p1,n), projectTexCoord(p2,n)};
    float minU=proj[0][0],maxU=proj[0][0],minV=proj[0][1],maxV=proj[0][1];
    for (int i=1;i<3;i++){minU=min(minU,proj[i][0]);maxU=max(maxU,proj[i][0]);minV=min(minV,proj[i][1]);maxV=max(maxV,proj[i][1]);}
    float du=maxU-minU, dv=maxV-minV;
    array<Vec2,3> uv={};
    for (int i=0;i<3;i++){uv[i][0]=(du>1e-6f)?((proj[i][0]-minU)/du):0;uv[i][1]=(dv>1e-6f)?((proj[i][1]-minV)/dv):0;}
    return uv;
}

static vector<string> extractVertexLines(const string& modelPath) {
    ifstream f(modelPath);
    if (!f.is_open()) return {};
    vector<string> lines;
    string line;
    bool first = true;
    while (getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        istringstream iss(line);
        string tag; iss >> tag;
        if (tag == "v") {
            string x, y, z;
            if (iss >> x >> y >> z) lines.push_back(x+" "+y+" "+z);
            continue;
        }
        if (first) {
            first = false;
            bool num = !tag.empty() && (isdigit((unsigned char)tag[0]) || tag[0]=='-' || tag[0]=='+');
            if (num) continue;
        }
    }
    if (lines.empty()) {
        f.clear(); f.seekg(0); first=true;
        while (getline(f,line)){if(first){first=false;continue;}if(!line.empty())lines.push_back(line);}
    }
    return lines;
}

} // namespace

// Scatter-specific writeOutput using the legacy planar-projection UV path
static void writeOutputLegacy(const list<string>& vertices, const string& file) {
    string outputPath = "../../figures/" + file;
    ofstream outFile(outputPath);
    if (!outFile.is_open()) {
        cerr << "Error: Could not open file " << outputPath << endl;
        return;
    }
    using Vec3 = array<float, 3>;
    using Vec2 = array<float, 2>;

    vector<Vec3> points;
    points.reserve(vertices.size());
    for (const auto& vertex : vertices) points.push_back(parseVec3(vertex));

    outFile << "# Generated by CG-SolarSystem\n";

    unordered_map<string, int> posToIndex;
    vector<Vec3> uniquePos;
    vector<Vec3> accumNormals;
    vector<Vec2> accumUV;
    vector<int> uvCount;

    auto makeKey = [](const Vec3& p) {
        ostringstream ss;
        ss << fixed << setprecision(6) << p[0] << "," << p[1] << "," << p[2];
        return ss.str();
    };

    for (size_t i = 0; i + 2 < points.size(); i += 3) {
        const Vec3& p0=points[i]; const Vec3& p1=points[i+1]; const Vec3& p2=points[i+2];
        Vec3 normal = crossVec(subtractVec(p1,p0), subtractVec(p2,p0));
        normalizeVec(normal);
        auto triUV = buildTriangleUVs(p0, p1, p2, normal);
        const Vec3 tp[3]={p0,p1,p2};
        for (int k=0;k<3;k++){
            string key=makeKey(tp[k]);
            int idx;
            auto it=posToIndex.find(key);
            if (it==posToIndex.end()){
                idx=(int)uniquePos.size(); posToIndex.emplace(key,idx);
                uniquePos.push_back(tp[k]); accumNormals.push_back({0,0,0});
                accumUV.push_back({0,0}); uvCount.push_back(0);
            } else idx=it->second;
            accumNormals[idx][0]+=normal[0]; accumNormals[idx][1]+=normal[1]; accumNormals[idx][2]+=normal[2];
            accumUV[idx][0]+=triUV[k][0]; accumUV[idx][1]+=triUV[k][1]; uvCount[idx]++;
        }
    }

    vector<Vec3> finalNormals(uniquePos.size());
    vector<Vec2> finalUVs(uniquePos.size());
    for (size_t i=0;i<uniquePos.size();i++){
        Vec3 n=accumNormals[i]; normalizeVec(n); finalNormals[i]=n;
        finalUVs[i]=(uvCount[i]>0)?Vec2{accumUV[i][0]/uvCount[i],accumUV[i][1]/uvCount[i]}:Vec2{0,0};
    }

    outFile << fixed << setprecision(6);
    for (size_t i=0;i<uniquePos.size();i++)
        outFile<<"v "<<uniquePos[i][0]<<' '<<uniquePos[i][1]<<' '<<uniquePos[i][2]<<'\n';
    for (size_t i=0;i<finalUVs.size();i++)
        outFile<<"vt "<<finalUVs[i][0]<<' '<<finalUVs[i][1]<<'\n';
    for (size_t i=0;i<finalNormals.size();i++)
        outFile<<"vn "<<finalNormals[i][0]<<' '<<finalNormals[i][1]<<' '<<finalNormals[i][2]<<'\n';

    for (size_t i=0;i+2<points.size();i+=3){
        int i0=posToIndex[makeKey(points[i])]+1;
        int i1=posToIndex[makeKey(points[i+1])]+1;
        int i2=posToIndex[makeKey(points[i+2])]+1;
        outFile<<"f "<<i0<<'/'<<i0<<'/'<<i0<<' '<<i1<<'/'<<i1<<'/'<<i1<<' '<<i2<<'/'<<i2<<'/'<<i2<<'\n';
    }
    outFile.close();
    cout << "Figure generated successfully: " << outputPath << endl;
    cout << "Total: " << vertices.size() << " vertices ("<<vertices.size()/3<<" triangles)" << endl;
}

static vector<string> loadModel(const string& modelFile) {
    string modelPath = "../../figures/" + modelFile;
    vector<string> lines = extractVertexLines(modelPath);
    if (lines.empty()) {
        string alt = modelPath;
        size_t dot = alt.find_last_of('.');
        if (dot != string::npos) {
            string ext = alt.substr(dot+1);
            if (ext == "3d") alt = alt.substr(0,dot)+".obj";
            else if (ext == "obj") alt = alt.substr(0,dot)+".3d";
        }
        if (alt != modelPath) lines = extractVertexLines(alt);
        if (lines.empty()) { cerr << "Error: Could not open model file " << modelPath << endl; return {}; }
    }
    return lines;
}

// ============================================================================
// MAIN
// ============================================================================

int main(int argc, char* argv[]) {
    if (argc < 3) {
        cerr << "Usage: " << argv[0] << " <shape> <parameters...> <output_file>" << endl;
        cerr << "  sphere   <radius> <slices> <stacks> <out>" << endl;
        cerr << "  box      <length> <divisions> <out>" << endl;
        cerr << "  cone     <radius> <height> <slices> <stacks> <out>" << endl;
        cerr << "  plane    <length> <divisions> <out>" << endl;
        cerr << "  cylinder <radius> <height> <slices> <stacks> <out>" << endl;
        cerr << "  icosphere <radius> <subdivisions> <out>" << endl;
        cerr << "  torus    <R> <r> <slices> <stacks> <out>" << endl;
        cerr << "  ring     <innerR> <outerR> <slices> <out>" << endl;
        cerr << "  octahedron <scale> <out>" << endl;
        cerr << "  bezier   <patchfile> <tessellation> <out>" << endl;
        cerr << "  scatter  <volume_shape> <volume_params...> <num> <model.obj> <smin> <smax> <out>" << endl;
        return 1;
    }

    list<string> arglist;
    string figure = argv[1];
    string file   = argv[argc - 1];
    for (int i = 2; i < argc - 1; i++) arglist.push_back(argv[i]);

    // ── shapes that use the proper VertList path ─────────────────────────────
    VertList verts;

    if (figure == "sphere") {
        if (arglist.size() != 3) { cerr << "Usage: sphere <radius> <slices> <stacks> <out>" << endl; return 1; }
        float radius = stof(arglist.front()); arglist.pop_front();
        int slices   = stoi(arglist.front()); arglist.pop_front();
        int stacks   = stoi(arglist.front());
        if (!verifyMetric("radius",radius,0.01)||!verifyMetric("slices",slices,1)||!verifyMetric("stacks",stacks,1)) return 1;
        generateSphere(radius, slices, stacks, verts);
        writeOutput(verts, file);

    } else if (figure == "box") {
        if (arglist.size() != 2) { cerr << "Usage: box <length> <divisions> <out>" << endl; return 1; }
        float length    = stof(arglist.front()); arglist.pop_front();
        int   divisions = stoi(arglist.front());
        if (!verifyMetric("length",length,0.01)||!verifyMetric("divisions",divisions,1)) return 1;
        generateBox(length, divisions, verts);
        writeOutput(verts, file);

    } else if (figure == "cone") {
        if (arglist.size() != 4) { cerr << "Usage: cone <radius> <height> <slices> <stacks> <out>" << endl; return 1; }
        float radius = stof(arglist.front()); arglist.pop_front();
        float height = stof(arglist.front()); arglist.pop_front();
        int slices   = stoi(arglist.front()); arglist.pop_front();
        int stacks   = stoi(arglist.front());
        if (!verifyMetric("radius",radius,0.01)||!verifyMetric("height",height,0.01)||!verifyMetric("slices",slices,1)||!verifyMetric("stacks",stacks,1)) return 1;
        generateCone(radius, height, slices, stacks, verts);
        writeOutput(verts, file);

    } else if (figure == "plane") {
        if (arglist.size() != 2) { cerr << "Usage: plane <length> <divisions> <out>" << endl; return 1; }
        float length    = stof(arglist.front()); arglist.pop_front();
        int   divisions = stoi(arglist.front());
        if (!verifyMetric("length",length,0.01)||!verifyMetric("divisions",divisions,1)) return 1;
        generatePlane(length, divisions, verts);
        writeOutput(verts, file);

    } else if (figure == "cylinder") {
        if (arglist.size() != 4) { cerr << "Usage: cylinder <radius> <height> <slices> <stacks> <out>" << endl; return 1; }
        float radius = stof(arglist.front()); arglist.pop_front();
        float height = stof(arglist.front()); arglist.pop_front();
        int slices   = stoi(arglist.front()); arglist.pop_front();
        int stacks   = stoi(arglist.front());
        if (!verifyMetric("radius",radius,0.01)||!verifyMetric("height",height,0.01)||!verifyMetric("slices",slices,1)||!verifyMetric("stacks",stacks,1)) return 1;
        generateCylinder(radius, height, slices, stacks, verts);
        writeOutput(verts, file);

    } else if (figure == "icosphere") {
        if (arglist.size() != 2) { cerr << "Usage: icosphere <radius> <subdivisions> <out>" << endl; return 1; }
        float radius = stof(arglist.front()); arglist.pop_front();
        int   subs   = stoi(arglist.front());
        if (!verifyMetric("radius",radius,0.01)||!verifyMetric("subdivisions",subs,0)) return 1;
        generateIcosphere(radius, subs, verts);
        writeOutput(verts, file);

    } else if (figure == "torus") {
        if (arglist.size() != 4) { cerr << "Usage: torus <R> <r> <slices> <stacks> <out>" << endl; return 1; }
        float R = stof(arglist.front()); arglist.pop_front();
        float r = stof(arglist.front()); arglist.pop_front();
        int slices = stoi(arglist.front()); arglist.pop_front();
        int stacks = stoi(arglist.front());
        generateTorus(R, r, slices, stacks, verts);
        writeOutput(verts, file);

    } else if (figure == "ring") {
        if (arglist.size() != 3) { cerr << "Usage: ring <innerR> <outerR> <slices> <out>" << endl; return 1; }
        float innerR = stof(arglist.front()); arglist.pop_front();
        float outerR = stof(arglist.front()); arglist.pop_front();
        int   slices  = stoi(arglist.front());
        if (!verifyMetric("innerRadius",innerR,0.0f)||!verifyMetric("outerRadius",outerR,0.01f)||!verifyMetric("slices",slices,3)) return 1;
        generateRing(innerR, outerR, slices, verts);
        writeOutput(verts, file);

    } else if (figure == "octahedron") {
        if (arglist.size() != 1) { cerr << "Usage: octahedron <scale> <out>" << endl; return 1; }
        float scale = stof(arglist.front());
        if (!verifyMetric("scale", scale, 0.01f)) return 1;
        generateOctahedron(verts, 0.0f, 0.0f, 0.0f, scale);
        writeOutput(verts, file);

    } else if (figure == "bezier") {
        if (arglist.size() != 2) { cerr << "Usage: bezier <patchfile> <tessellation> <out>" << endl; return 1; }
        string patchFile = arglist.front(); arglist.pop_front();
        int tess = stoi(arglist.front());
        if (!verifyMetric("tessellation",tess,1)) return 1;
        generateBezier(patchFile, tess, verts);
        writeOutput(verts, file);

    // ── scatter — legacy list<string> path ───────────────────────────────────
    } else if (figure == "scatter") {
        if (arglist.empty()) { cerr << "scatter: missing volume shape" << endl; return 1; }
        string shape = arglist.front(); arglist.pop_front();

        int numParams = 0;
        if      (shape == "sphere")   numParams = 2;
        else if (shape == "torus")    numParams = 3;
        else if (shape == "plane")    numParams = 2;
        else if (shape == "cylinder") numParams = 4;
        else if (shape == "box")      numParams = 2;
        else { cerr << "scatter: unknown volume shape '" << shape << "'" << endl; return 1; }

        if ((int)arglist.size() < numParams + 4) {
            cerr << "scatter: not enough arguments for shape '" << shape << "'" << endl; return 1;
        }

        vector<float> params;
        for (int i = 0; i < numParams; i++) { params.push_back(stof(arglist.front())); arglist.pop_front(); }

        int    num       = stoi(arglist.front()); arglist.pop_front();
        string modelFile =      arglist.front();  arglist.pop_front();
        float  scaleMin  = stof(arglist.front()); arglist.pop_front();
        float  scaleMax  = stof(arglist.front()); arglist.pop_front();

        vector<string> modelVerts = loadModel(modelFile);
        if (modelVerts.empty()) return 1;

        srand(42);
        list<string> legacyVerts;
        for (int i = 0; i < num; i++) {
            ScatterSample pos;
            if (!sampleVolume(shape, params, pos)) return 1;
            float scale = scaleMin + rand01() * (scaleMax - scaleMin);
            float rx = rand01()*2.0f*M_PI, ry = rand01()*2.0f*M_PI, rz = rand01()*2.0f*M_PI;
            for (const string& v : modelVerts)
                legacyVerts.push_back(transformVertex(v, pos.x, pos.y, pos.z, rx, ry, rz, scale));
        }
        writeOutputLegacy(legacyVerts, file);

    } else {
        cerr << "Unknown figure type: " << figure << endl;
        return 1;
    }

    return 0;
}
